# I am interested in seeing profiles/employment history of people in Trenton NJ. 
library(DBI)
library(dbplyr)
library(tidyverse)
library(bgi)
library(openxlsx)
library(readxl)

con <- DBI::dbConnect(odbc::odbc(), Driver = "SnowflakeDSIIDriver", 
                      Server = "pca67849.snowflakecomputing.com", Uid = "KIM_KREISS", 
                      Pwd = Sys.getenv('pwd'))

postings_meta <- query_table_sf(con, "PDL_WORKING", "JAN_24", "LOCATION") %>%
  filter(LOCALITY=="trenton" & REGION == "new jersey") %>%
  collect()

trenton_ids <- query_table_sf(con, "PDL_WORKING", "JAN_24", "LOCATION") %>%
  filter(LOCALITY=="trenton" & REGION == "new jersey") 

trenton_educations <- query_table_sf(con, "PDL_WORKING", "JAN_24", "EDUCATION") %>%
  inner_join(trenton_ids, by = "ID") %>%
  collect()

mercer <- trenton_educations %>% 
  filter(SCHOOL_RAW=='mercer county community college') %>% 
  select(ID) %>% 
  distinct()

nj_postings <- query_table_sf(con, "EMSI_BURNING_GLASS_INSTITUTE", "US", "POSTINGS") %>% 
  filter(POSTED >= as.Date("2023-01-01") & POSTED <= as.Date("2023-12-31") & STATE==34) %>% 
  collect() %>% 
  filter(COMPANY_IS_STAFFING ==FALSE ) 

################################################# 
# OPRA data analysis 
#################################################

opra_updated_jobs <- read.xlsx("kim-projects/data/OPRA Request C25235 EO327 4 Yr Degree Titles.xlsx", sheet = 1, startRow = 2)
opra_all4yr_jobs <- read.xlsx("kim-projects/data/OPRA Request C25235 EO327 4 Yr Degree Titles.xlsx", sheet = 2, startRow = 2)

## What share of postings are from a government firm in NJ? 
nj_postings_firms <- nj_postings %>% 
  select(COMPANY_NAME) %>% 
  distinct()


## need to figure out how to more accurately identify government jobs in NJ 
govt_firms <- c("State Of New Jersey", "City Of", "County Of", "District", "Authority","Commission", 
                "New Jersey Courts", "New Jersey Economic Development Authority", "New Jersey Housing Mortgage Finance Agency", 
                "Nj Transit", "Non-Federal Agency", "City Hall", "Port Newark Container Terminal", "New Jersey Department of Health", 
                "Library", "New Jersey Division","Department", "Township", "Town Of", "County Board","Borough Of")
NJ_counties<-c('Atlantic County','Bergen County','Burlington County','Camden County','Cape May County','Cumberland County','Essex County',
'Gloucester County','Hudson County','Hunterdon County','Mercer County','Middlesex County','Monmouth County','Morris County',
'Ocean County','Passaic County','Salem County','Somerset County','Sussex County','Union County','Warren County')
school_related <- c("District", "Charter School", "Community College", "Board of Education", "Regional High School",
                    "Elementary School", "Middle School", "Public School", "School District", 
                    "Kean University", "Monclair", "Ramapo", "New Jersey City University", "Rowan", "State Library", 
                    "Stockton", "The College of New Jersey", "Thomas Edison State University", "William Paterson", "Rutgers", 
                    "New Jersey Institute of Technology", "New Jersey Transit", "South Jersey Port Corporation", "State Colleges")

NJ_towns <- c(
  "Absecon",
  "Allendale",
  "Allenhurst",
  "Allentown",
  "Alpha",
  "Alpine",
  "Andover",
  "Asbury Park",
  "Atlantic City",
  "Atlantic Highlands",
  "Audubon",
  "Audubon Park",
  "Avalon",
  "Avon-by-the-Sea",
  "Barnegat",
  "Barrington",
  "Bay Head",
  "Bayonne",
  "Beach Haven",
  "Beachwood",
  "Beattystown",
  "Beckett",
  "Belford",
  "Belleville",
  "Bellmawr",
  "Belmar",
  "Belvidere",
  "Bergenfield",
  "Berkeley Heights",
  "Berlin",
  "Bernardsville",
  "Beverly",
  "Blackwood",
  "Blairstown",
  "Blawenburg",
  "Bloomingdale",
  "Bloomsbury",
  "Bogota",
  "Boonton",
  "Bordentown",
  "Bound Brook",
  "Bradley Beach",
  "Branchville",
  "Brant Beach",
  "Brick",
  "Bridgeport",
  "Bridgeton",
  "Bridgewater",
  "Brielle",
  "Brigantine",
  "Broadway",
  "Brooklawn",
  "Browns Mills",
  "Budd Lake",
  "Buena",
  "Burlington",
  "Butler",
  "Caldwell",
  "Califon",
  "Camden",
  "Cape May",
  "Cape May Court House",
  "Cape May Point",
  "Carlstadt",
  "Carteret",
  "Cedar Grove",
  "Cedar Knolls",
  "Cedarville",
  "Chatham",
  "Chatsworth",
  "Cherry Hill",
  "Chester",
  "Chesterfield",
  "Clark",
  "Clarksboro",
  "Clayton",
  "Clementon",
  "Cliffside Park",
  "Cliffwood",
  "Clifton",
  "Clinton",
  "Closter",
  "Collings Lakes",
  "Collingswood",
  "Colonia",
  "Colts Neck",
  "Columbia",
  "Columbus",
  "Concordia",
  "Corbin City",
  "Cranbury",
  "Cranford",
  "Cream Ridge",
  "Cresskill",
  "Crestwood Village",
  "Dayton",
  "Deal",
  "Deepwater",
  "Deerfield Street",
  "Delanco",
  "Delaware",
  "Delmont",
  "Delran",
  "Demarest",
  "Dennisville",
  "Denville",
  "Deptford",
  "Dorchester",
  "Dorothy",
  "Dover",
  "Dumont",
  "Dunellen",
  "East Brunswick",
  "East Hanover",
  "East Newark",
  "East Orange",
  "East Rutherford",
  "Eatontown",
  "Echelon",
  "Edgewater",
  "Edison",
  "Egg Harbor City",
  "Egg Harbor Township",
  "Elizabeth",
  "Elmer",
  "Elmwood Park",
  "Elwood",
  "Emerson",
  "Englewood",
  "Englewood Cliffs",
  "Englishtown",
  "Erlton-Ellisburg",
  "Erma",
  "Essex Fells",
  "Estell Manor",
  "Ewing",
  "Fair Haven",
  "Fair Lawn",
  "Fairfield",
  "Fairton",
  "Fairview",
  "Fanwood",
  "Far Hills",
  "Farmingdale",
  "Fieldsboro",
  "Flemington",
  "Florence",
  "Florham Park",
  "Folsom",
  "Fords",
  "Forked River",
  "Fort Dix",
  "Fort Lee",
  "Franklin",
  "Franklin Lakes",
  "Franklin Park",
  "Freehold",
  "Frenchtown",
  "Galloway",
  "Garfield",
  "Garwood",
  "Gibbsboro",
  "Gibbstown",
  "Gillette",
  "Gladstone",
  "Glassboro",
  "Glasser",
  "Glen Gardner",
  "Glen Ridge",
  "Glen Rock",
  "Glendora",
  "Glenwood",
  "Gloucester City",
  "Goshen",
  "Great Meadows",
  "Green Brook",
  "Green Creek",
  "Green Village",
  "Greendell",
  "Greenwich",
  "Guttenberg",
  "Hackensack",
  "Hackettstown",
  "Haddon Heights",
  "Haddonfield",
  "Hainesport",
  "Haledon",
  "Hamburg",
  "Hamilton",
  "Hammonton",
  "Hampton",
  "Hancocks Bridge",
  "Hancocks Bridge",
  "Hanover",
  "Harding",
  "Hardwick",
  "Hardyston",
  "Harrington Park",
  "Harrison",
  "Harvey Cedars",
  "Hasbrouck Heights",
  "Haskell",
  "Haworth",
  "Hawthorne",
  "Hazlet",
  "Heislerville",
  "Helmetta",
  "Hewitt",
  "Hibernia",
  "High Bridge",
  "Highland Lakes",
  "Highland Park",
  "Highlands",
  "Hightstown",
  "Hillsborough",
  "Hillsdale",
  "Hillside",
  "Ho-Ho-Kus",
  "Hoboken",
  "Holmdel",
  "Hopatcong",
  "Hope",
  "Hopewell",
  "Howell",
  "Hudson County",
  "Hunterdon County",
  "Irvington",
  "Iselin",
  "Island Heights",
  "Jackson",
  "Jamesburg",
  "Jefferson",
  "Jersey City",
  "Jobstown",
  "Johnsonburg",
  "Keansburg",
  "Kearny",
  "Keasbey",
  "Kendall Park",
  "Kenilworth",
  "Kenvil",
  "Keyport",
  "Kingston",
  "Kinnelon",
  "Lafayette",
  "Lake Como",
  "Lake Hiawatha",
  "Lake Hopatcong",
  "Lakehurst",
  "Lakewood",
  "Lambertville",
  "Landing",
  "Landisville",
  "Lanoka Harbor",
  "Laurence Harbor",
  "Lavallette",
  "Lawnside",
  "Lawrence",
  "Lawrenceville",
  "Lebanon",
  "Ledgewood",
  "Leeds Point",
  "Leesburg",
  "Leonardo",
  "Leonia",
  "Liberty Corner",
  "Lincoln Park",
  "Lincroft",
  "Linden",
  "Lindenwold",
  "Linwood",
  "Little Egg Harbor",
  "Little Falls",
  "Little Ferry",
  "Little Silver",
  "Livingston",
  "Lodi",
  "Long Beach",
  "Long Branch",
  "Long Valley",
  "Longport",
  "Lumberton",
  "Lyndhurst",
  "Lyons",
  "Madison",
  "Magnolia",
  "Mahwah",
  "Malaga",
  "Manahawkin",
  "Manalapan",
  "Manasquan",
  "Manchester",
  "Mantoloking",
  "Mantua",
  "Manville",
  "Maple Shade",
  "Maplewood",
  "Margate City",
  "Marlboro",
  "Marlton",
  "Marmora",
  "Martinsville",
  "Matawan",
  "Maurice River",
  "Mauricetown",
  "Mays Landing",
  "Maywood",
  "McAfee",
  "Medford",
  "Medford Lakes",
  "Mendham",
  "Merchantville",
  "Metuchen",
  "Mickleton",
  "Middlesex",
  "Middletown",
  "Middleville",
  "Midland Park",
  "Milford",
  "Millburn",
  "Millington",
  "Millstone",
  "Milltown",
  "Millville",
  "Milmay",
  "Mine Hill",
  "Minotola",
  "Mizpah",
  "Monmouth Beach",
  "Monmouth Junction",
  "Monroe",
  "Monroeville",
  "Montague",
  "Montclair",
  "Montgomery",
  "Montvale",
  "Montville",
  "Moonachie",
  "Moorestown",
  "Morganville",
  "Morris Plains",
  "Morristown",
  "Mount Arlington",
  "Mount Ephraim",
  "Mount Freedom",
  "Mount Holly",
  "Mount Laurel",
  "Mount Royal",
  "Mount Tabor",
  "Mountain Lakes",
  "Mountainside",
  "Mullica Hill",
  "Murray Hill",
  "Mystic Island",
  "National Park",
  "Navesink",
  "Neptune",
  "Neshanic Station",
  "Netcong",
  "New Brunswick",
  "New Egypt",
  "New Gretna",
  "New Lisbon",
  "New Milford",
  "New Monmouth",
  "New Providence",
  "New Vernon",
  "Newark",
  "Newfield",
  "Newfoundland",
  "Newport",
  "Newton",
  "Newtonville",
  "Norma",
  "Normandy Beach",
  "North Arlington",
  "North Bergen",
  "North Brunswick",
  "North Caldwell",
  "North Cape May",
  "North Haledon",
  "North Hanover",
  "North Middletown",
  "North Plainfield",
  "North Wildwood",
  "Northfield",
  "Northvale",
  "Norwood",
  "Nutley",
  "Oak Ridge",
  "Oakhurst",
  "Oakland",
  "Oaklyn",
  "Ocean",
  "Ocean City",
  "Ocean Gate",
  "Ocean Grove",
  "Ocean View",
  "Oceanport",
  "Oceanville",
  "Ogdensburg",
  "Old Bridge",
  "Old Tappan",
  "Oldwick",
  "Oradell",
  "Orange",
  "Oxford",
  "Palermo",
  "Palisades Park",
  "Palmyra",
  "Paramus",
  "Park Ridge",
  "Parsippany-Troy Hills",
  "Passaic",
  "Paterson",
  "Paulsboro",
  "Peapack and Gladstone",
  "Pedricktown",
  "Pemberton",
  "Pennington",
  "Penns Grove",
  "Pennsauken",
  "Pennsville",
  "Pequannock",
  "Perth Amboy",
  "Phillipsburg",
  "Pilesgrove",
  "Pine Beach",
  "Pine Brook",
  "Pine Hill",
  "Pine Valley",
  "Piscataway",
  "Pitman",
  "Pittsgrove",
  "Plainfield",
  "Plainsboro",
  "Pleasantville",
  "Pluckemin",
  "Point Pleasant",
  "Point Pleasant Beach",
  "Pomona",
  "Pompton Lakes",
  "Pompton Plains",
  "Port Elizabeth",
  "Port Monmouth",
  "Port Murray",
  "Port Norris",
  "Port Reading",
  "Port Republic",
  "Pottersville",
  "Princeton",
  "Princeton Junction",
  "Prospect Park",
  "Quakertown",
  "Quinton",
  "Rahway",
  "Ramsey",
  "Rancocas",
  "Randolph",
  "Raritan",
  "Readington",
  "Red Bank",
  "Richland",
  "Richwood",
  "Ridgefield",
  "Ridgefield Park",
  "Ridgewood",
  "Ringoes",
  "Ringwood",
  "Rio Grande",
  "River Edge",
  "River Vale",
  "Riverdale",
  "Riverside",
  "Riverton",
  "Robbinsville",
  "Rochelle Park",
  "Rockaway",
  "Rockleigh",
  "Rocky Hill",
  "Roebling",
  "Roosevelt",
  "Roseland",
  "Roselle",
  "Roselle Park",
  "Rosemont",
  "Rosenhayn",
  "Rumson",
  "Runnemede",
  "Rutherford",
  "Saddle Brook",
  "Saddle River",
  "Salem",
  "Sayreville",
  "Scotch Plains",
  "Sea Bright",
  "Sea Girt",
  "Sea Isle City",
  "Seabrook Farms",
  "Seaside Heights",
  "Seaside Park",
  "Secaucus",
  "Sergeantsville",
  "Sewaren",
  "Sewell",
  "Shamong",
  "Shiloh",
  "Ship Bottom",
  "Short Hills",
  "Shrewsbury",
  "Sicklerville",
  "Skillman",
  "Smithville",
  "Somerdale",
  "Somers Point",
  "Somerset",
  "Somerville",
  "South Amboy",
  "South Belmar",
  "South Bound Brook",
  "South Brunswick",
  "South Dennis",
  "South Hackensack",
  "South Harrison",
  "South Orange",
  "South Plainfield",
  "South River",
  "South Toms River",
  "South Vineland",
  "Southampton",
  "Sparta",
  "Spotswood",
  "Spring Lake",
  "Spring Lake Heights",
  "Springfield",
  "Stanhope",
  "Stanton",
  "Stewartsville",
  "Stillwater",
  "Stirling",
  "Stockholm",
  "Stockton",
  "Stone Harbor",
  "Stratford",
  "Strathmere",
  "Succasunna",
  "Summit",
  "Sussex",
  "Swartswood",
  "Swedesboro",
  "Tabernacle",
  "Teaneck",
  "Tenafly",
  "Tennent",
  "Teterboro",
  "Thorofare",
  "Three Bridges",
  "Tinton Falls",
  "Titusville",
  "Toms River",
  "Totowa",
  "Towaco",
  "Township of Washington",
  "Tranquility",
  "Trenton",
  "Tuckahoe",
  "Tuckerton",
  "Turnersville",
  "Twin Rivers",
  "Two Bridges",
  "Union",
  "Union Beach",
  "Union City",
  "Upper Deerfield",
  "Upper Freehold",
  "Upper Montclair",
  "Upper Saddle River",
  "Upper Stewartsville",
  "Upper Township",
  "Upper Twp",
  "Vauxhall",
  "Ventnor City",
  "Vernon",
  "Verona",
  "Vienna",
  "Villas",
  "Vincentown",
  "Vineland",
  "Voorhees",
  "Waldwick",
  "Wall",
  "Wall Township",
  "Wallington",
  "Walpack",
  "Wanaque",
  "Waretown",
  "Warren",
  "Washington",
  "Washington Township",
  "Watchung",
  "Waterford",
  "Wayne",
  "Weehawken",
  "Weekstown",
  "Wenonah",
  "West Amwell",
  "West Atlantic City",
  "West Belmar",
  "West Berlin",
  "West Caldwell",
  "West Cape May",
  "West Collingswood",
  "West Creek",
  "West Long Branch",
  "West Milford",
  "West New York",
  "West Orange",
  "West Paterson",
  "West Trenton",
  "West Wildwood",
  "West Windsor",
  "Westampton",
  "Western Area",
  "Westfield",
  "Westmont",
  "Westville",
  "Westwood",
  "Wharton",
  "Whippany",
  "White Horse",
  "White House Station",
  "Whitehouse",
  "Whitehouse Station",
  "Whitesboro",
  "Whiting",
  "Wildwood",
  "Wildwood Crest",
  "Willingboro",
  "Windsor",
  "Winfield Park",
  "Winslow",
  "Wood-Ridge",
  "Woodbine",
  "Woodbridge",
  "Woodbury",
  "Woodbury Heights",
  "Woodcliff Lake",
  "Woodland Park",
  "Woodlynne",
  "Woodstown",
  "Woolwich",
  "Wrightstown",
  "Wyckoff",
  "Yardville",
  "Zarephath"
)


filter_phrases <- c(govt_firms,school_related)

govt_firms_source <- nj_postings%>%  
  filter(Reduce(`|`, lapply(filter_phrases, function(phrase) grepl(phrase, COMPANY_NAME, ignore.case = TRUE))) | 
           (COMPANY_NAME %in% NJ_counties) | (COMPANY_NAME %in% NJ_towns)) %>% 
  filter(!str_detect(COMPANY_NAME, "Foundation")) %>%
  filter(!str_detect(COMPANY_NAME, "United States Department")) %>%  
  filter(!str_detect(COMPANY_NAME, "Sales Department")) %>% 
  filter(!str_detect(COMPANY_NAME, "Department Store")) %>%
  filter(!str_detect(COMPANY_NAME, "Animal Clinic")) %>%
  filter(!str_detect(COMPANY_NAME, "Animal Hospital")) %>%
  filter(!str_detect(COMPANY_NAME, "Central Avenue Special Improvement")) %>% 
  filter(!str_detect(COMPANY_NAME, "Head Start")) %>% 
  filter(!str_detect(COMPANY_NAME, "Adult Day Center")) %>% 
  filter(!str_detect(COMPANY_NAME, "Parts Authority")) %>% 
  filter(!str_detect(COMPANY_NAME, "Citco Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Rose's Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "U.S Environmental Protection Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "The Arc")) %>% 
  filter(!str_detect(COMPANY_NAME, "Arc Mercer")) 


unique_gfs <- govt_firms_source %>% 
  select(COMPANY_NAME) %>% 
  distinct()
nrow(govt_firms_source)/nrow(nj_postings)







filter(!str_detect(COMPANY_NAME, "Head Start")) %>% 
  filter(!str_detect(COMPANY_NAME, "Adult Day Center")) %>% 
  filter(!str_detect(COMPANY_NAME, "Parts Authority")) %>% 
  filter(!str_detect(COMPANY_NAME, "Citco Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Rose's Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "U.S Environmental Protection Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "The Arc")) %>% 
  filter(!str_detect(COMPANY_NAME, "Arc Mercer"))  %>% 
  filter(!str_detect(COMPANY_NAME, "Sas Retail Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Farm Service Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Diversified Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Wawa Agency")) %>% 
  filter(!str_detect(COMPANY_NAME, "Ames Community")) %>% 
  filter(!str_detect(COMPANY_NAME, "Medical Center")) %>% 
  filter(!str_detect(COMPANY_NAME, "Care")) %>% 
  filter(!str_detect(COMPANY_NAME, "Acton Academy")) %>% 
  filter(!str_detect(COMPANY_NAME, "Urology")) %>% 
  filter(!str_detect(COMPANY_NAME, "Dental")) %>% 
  filter(!str_detect(COMPANY_NAME, "Animal")) %>% 
  filter(!str_detect(COMPANY_NAME, "Acelero")) %>% 
  filter(!str_detect(COMPANY_NAME, "Amsalem")) %>% 
  filter(!str_detect(COMPANY_NAME, "Dermatology")) %>% 
  filter(!str_detect(COMPANY_NAME, "Acelero")) %>% 
  filter(!str_detect(COMPANY_NAME, "Vascular")) %>% 
  filter(!str_detect(COMPANY_NAME, "Endodontics")) %>%
  filter(!str_detect(COMPANY_NAME, "Mental Health")) %>%
  filter(!str_detect(COMPANY_NAME, "Healthcare")) %>%
  filter(!str_detect(COMPANY_NAME, "Digestive")) %>%
  filter(!str_detect(COMPANY_NAME, "Pediatrics")) %>%
  filter(!str_detect(COMPANY_NAME, "Hunterdon Helpline")) %>%
  filter(!str_detect(COMPANY_NAME, "Hunterdon Hospital")) %>%
  filter(!str_detect(COMPANY_NAME, "Hudson Group")) %>%
  filter(!str_detect(COMPANY_NAME, "Masonic Village")) %>%
  filter(!str_detect(COMPANY_NAME, "Tender Smiles")) %>%
  filter(!str_detect(COMPANY_NAME, "Ramapo Communication Corp.")) %>%
  filter(!str_detect(COMPANY_NAME, "Apparel")) %>%
  filter(!str_detect(COMPANY_NAME, "Chiropractic")) %>%
  filter(!str_detect(COMPANY_NAME, "Cardiology")) %>%
  filter(!str_detect(COMPANY_NAME, "Swim School")) %>%
  filter(!str_detect(COMPANY_NAME, "Salem Press")) %>%
  filter(!str_detect(COMPANY_NAME, "Monmouth Telecom")) %>%
  filter(!str_detect(COMPANY_NAME, "Veterinary Center Of Morris County")) %>%
  filter(!str_detect(COMPANY_NAME, "Sussexpress")) %>%
  filter(!str_detect(COMPANY_NAME, "Brewing Co")) %>%
  filter(!str_detect(COMPANY_NAME, "Commercial District Services")) %>%
  filter(!str_detect(COMPANY_NAME, "Welders")) 



# posts_nj_govt_2023 <- query_table_sf(con, "EMSI_BURNING_GLASS_INSTITUTE", "US", "POSTINGS") %>%
#   filter(sql("ARRAY_CONTAINS('Government'::VARIANT, SOURCE_TYPES)")) %>% # Looking at just postings  featured on a company website 
#   #filter(sql("ARRAY_CONTAINS('Company'::VARIANT, SOURCE_TYPES)"), DUPLICATES == 0) %>% ... #looking at postings JUST on a company website 
#   #select(ID, POSTED, SOURCE_TYPES,COMPANY_NAME, SOC_5, SOC_5_NAME, SOC_2, SOC_2_NAME, NAICS2, NAICS2_NAME, STATE) %>% 
#   filter(POSTED >= as.Date("2023-01-01") & POSTED <= as.Date("2023-12-31"), STATE==34) %>% 
#   mutate(year = lubridate::year(POSTED))%>% 
#   collect() %>% 
#   filter(COMPANY_IS_STAFFING ==FALSE )
# 
# firms_nj <- posts_nj_govt_2023 %>% 
#   select(COMPANY_NAME) %>% 
#   unique()

# some weird ones that would not count: 
#Allegheny Valley School
#Adult Day Center Of Somerset County
#Ames Community School District
# British Swim School
# Cumberland Dairy

