---
output:
  pdf_document: default
  html_document: default
---
```{r, warning = F, message = F, echo = F, results='hide', fig.show='hide'}
#source(paste0(here::here(),"/scripts/global-variables.R"))
source(paste0(here::here(),"/scripts/04a-causal-analysis-person-ct-nj.R"))
```

```{r}

#########################
# Regression 
#########################

government_hires <- all_govt_hiring %>% 
  mutate(month = 1:n()) %>% 
  pivot_longer(cols = c(hires_n_nj, hires_n_ct), names_to = "state", values_to = "hires") %>%
  mutate(after_policy = as.numeric(START_DATE >= "2023-10-01"), 
         treated = if_else(state == 'hires_n_nj', 1, 0))

did_model <- lm(hires ~  treated * month, data = government_hires)
summary(did_model)

did_model2 <- lm(hires ~  treated + after_policy + treated*after_policy, data = government_hires)
summary(did_model2)

government_hires_sa <- all_hiringSeasonAdj_df %>% 
  mutate(month = 1:n()) %>% 
  pivot_longer(cols = c(aa_nj_season_adj_hires, aa_ct_season_adj_hires), names_to = "state", values_to = "hires") %>%
  mutate(after_policy = as.numeric(year >= "2023-10-01"), 
         treated = if_else(state == 'aa_nj_season_adj_hires', 1, 0))

did_model_sa <- lm(hires ~  treated * month, data = government_hires_sa)
summary(did_model_sa)

did_model_sa2 <- lm(hires ~  treated + after_policy + treated*after_policy, data = government_hires_sa)
summary(did_model_sa2)
```

```{r, results='asis', echo=F}
library(stargazer)

stargazer(did_model2, did_model_sa2)

```


```{r,results='asis', echo=F}

#########################
# Regression 
#########################


government_hires <- all_govt_hiring %>% 
    filter(START_DATE >= "2021-01-01") %>% 
  mutate(month = 1:n()) %>% 
  pivot_longer(cols = c(hires_n_nj, hires_n_ct), names_to = "state", values_to = "hires") %>%
  mutate(after_policy = as.numeric(START_DATE >= "2023-10-01"), 
         treated = if_else(state == 'hires_n_nj', 1, 0))

did_model <- lm(hires ~  treated * month, data = government_hires)
summary(did_model)

did_model2 <- lm(hires ~  treated + after_policy + treated*after_policy, data = government_hires)
summary(did_model2)

government_hires_sa <- all_hiringSeasonAdj_df %>% 
    filter(year >= "2021-01-01") %>% 
  mutate(month = 1:n()) %>% 
  pivot_longer(cols = c(aa_nj_season_adj_hires, aa_ct_season_adj_hires), names_to = "state", values_to = "hires") %>%
  mutate(after_policy = as.numeric(year >= "2023-10-01"), 
         treated = if_else(state == 'aa_nj_season_adj_hires', 1, 0))

did_model_sa <- lm(hires ~  treated * month, data = government_hires_sa)
summary(did_model_sa)

did_model_sa2 <- lm(hires ~  treated + after_policy + treated*after_policy, data = government_hires_sa)
summary(did_model_sa2)

```


```{r, results='asis', echo=F}
library(stargazer)

stargazer(did_model2, did_model_sa2, heading=F)

```






\begin{equation}
Y_{it} = \beta_0 + \beta_1 \text{Treatment}_i + \beta_2 \text{Post}_t + \beta_3 (\text{Treatment}_i \times \text{Post}_t) + \epsilon_{it}
\end{equation}
